version: '3'

services:
  chat:
    restart: always
    image: raptor_info_chat_img
    environment:
      - TZ=Asia/Tokyo

    container_name: 'raptor_chat'
    volumes:
      - ../../src:/home/nomura/
      - ../../log:/var/log/uwsgi:rw
    command: >
      bash -c "
        uwsgi --ini uwsgi/uwsgi.ini
        wait
        bash
      "
    networks:
      - raptorlink
    ports:
      - "5000:5000"
    tty: true

  dev:
    restart: always
    image: raptor_info_chat_img
    environment:
      - TZ=Asia/Tokyo

    container_name: 'raptor_chat_dev'
    volumes:
      - ../../src:/home/nomura/
      - ../../log:/var/log/uwsgi:rw
    command: >
      bash -c "
        wait
        bash
      "
    networks:
      - raptorlink
    ports:
      - "5000:5000"
    tty: true

networks:
  raptorlink:
    external: true
    name: "RaptorLink"
